version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        ports:
            - "3000:3000"
        networks:
            - app-network

    db:
        image: mongo:3.6.17
        container_name: db
        restart: unless-stopped
        ports:
            - "7777:7777"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

