version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        ports:
            - "3000:3000"
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:3.6.17
        restart: unless-stopped
        ports:
            - "27017:27017"
