version: '3'
services:
    app:
        build: ./
        restart: always
        container_name: app
        volumes:
            - .:/photo_gallery
        ports:
            - "3000:3000"
        links:
            - mongo
    mongo:
        container_name: photos
        image: mongo
        volumes:
            - .:/app
        ports:
            - "27017:27017"