version: "3"
services:
    app:
        build: ./
        container_name: app
        volumes:
            - .:/fake_sns
        ports:
            - "3000:3000"
        links:
            - db
    db:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
